package com.m2team.phuotstory.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.m2team.phuotstory.model.Story;
import com.m2team.phuotstory.model.Level;

import com.m2team.phuotstory.model.StoryDao;
import com.m2team.phuotstory.model.LevelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyDaoConfig;
    private final DaoConfig levelDaoConfig;

    private final StoryDao storyDao;
    private final LevelDao levelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        storyDao = new StoryDao(storyDaoConfig, this);
        levelDao = new LevelDao(levelDaoConfig, this);

        registerDao(Story.class, storyDao);
        registerDao(Level.class, levelDao);
    }
    
    public void clear() {
        storyDaoConfig.getIdentityScope().clear();
        levelDaoConfig.getIdentityScope().clear();
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

}
