package com.m2team.phuotstory.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LEVEL".
 */
public class Level {

    private Long id;
    private String name;
    private Long levelRoad;
    private Long levelStory;

    public Level() {
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, String name, Long levelRoad, Long levelStory) {
        this.id = id;
        this.name = name;
        this.levelRoad = levelRoad;
        this.levelStory = levelStory;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getLevelRoad() {
        return levelRoad;
    }

    public void setLevelRoad(Long levelRoad) {
        this.levelRoad = levelRoad;
    }

    public Long getLevelStory() {
        return levelStory;
    }

    public void setLevelStory(Long levelStory) {
        this.levelStory = levelStory;
    }

}
