package com.m2team.phuotstory.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORY".
 */
public class Story {

    private Long id;
    private String title;
    private String description;
    private String shortTitleLocation;
    private String fullLocationList;
    private String photoUri;
    private String friends;
    private String feeling;
    private Long travelTime;
    private Long createdTime;
    private Double distance;

    public Story() {
    }

    public Story(Long id) {
        this.id = id;
    }

    public Story(Long id, String title, String description, String shortTitleLocation, String fullLocationList, String photoUri, String friends, String feeling, Long travelTime, Long createdTime, Double distance) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.shortTitleLocation = shortTitleLocation;
        this.fullLocationList = fullLocationList;
        this.photoUri = photoUri;
        this.friends = friends;
        this.feeling = feeling;
        this.travelTime = travelTime;
        this.createdTime = createdTime;
        this.distance = distance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getShortTitleLocation() {
        return shortTitleLocation;
    }

    public void setShortTitleLocation(String shortTitleLocation) {
        this.shortTitleLocation = shortTitleLocation;
    }

    public String getFullLocationList() {
        return fullLocationList;
    }

    public void setFullLocationList(String fullLocationList) {
        this.fullLocationList = fullLocationList;
    }

    public String getPhotoUri() {
        return photoUri;
    }

    public void setPhotoUri(String photoUri) {
        this.photoUri = photoUri;
    }

    public String getFriends() {
        return friends;
    }

    public void setFriends(String friends) {
        this.friends = friends;
    }

    public String getFeeling() {
        return feeling;
    }

    public void setFeeling(String feeling) {
        this.feeling = feeling;
    }

    public Long getTravelTime() {
        return travelTime;
    }

    public void setTravelTime(Long travelTime) {
        this.travelTime = travelTime;
    }

    public Long getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

}
